[package]
name = "gull"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gtk = { version = "0.5.1", package = "gtk4", features = ["v4_6"] }
gl = "0.14"
epoxy = "0.1.0"
libloading="0.7.4"
